import enum
import uuid

from sqlalchemy import Enum, ForeignKey, Index, Numeric, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TenantScopedMixin, TimestampMixin


class RecommendationStatus(str, enum.Enum):
    OPEN = "open"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"
    DISMISSED = "dismissed"


class RiskLevel(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class EffortLevel(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RecommendationCategory(str, enum.Enum):
    WASTE_DETECTION = "waste_detection"
    RIGHT_SIZING = "right_sizing"
    RATE_OPTIMIZATION = "rate_optimization"
    GOVERNANCE = "governance"


# Valid state transitions
VALID_STATUS_TRANSITIONS: dict[RecommendationStatus, list[RecommendationStatus]] = {
    RecommendationStatus.OPEN: [
        RecommendationStatus.APPROVED,
        RecommendationStatus.REJECTED,
        RecommendationStatus.DISMISSED,
    ],
    RecommendationStatus.APPROVED: [
        RecommendationStatus.EXECUTED,
        RecommendationStatus.REJECTED,
    ],
    RecommendationStatus.REJECTED: [
        RecommendationStatus.OPEN,
    ],
    RecommendationStatus.EXECUTED: [],
    RecommendationStatus.DISMISSED: [
        RecommendationStatus.OPEN,
    ],
}


class Recommendation(Base, TenantScopedMixin, TimestampMixin):
    """Cost optimization recommendation generated by the rule engine."""

    __tablename__ = "recommendations"
    __table_args__ = (
        Index("ix_recommendations_status", "status"),
        Index("ix_recommendations_category", "category"),
        Index("ix_recommendations_resource", "resource_db_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    resource_db_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("resources.id", ondelete="SET NULL"),
        nullable=True,
    )
    rule_id: Mapped[str] = mapped_column(String(100), nullable=False)
    category: Mapped[RecommendationCategory] = mapped_column(
        Enum(RecommendationCategory, name="recommendation_category"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    estimated_monthly_savings: Mapped[float] = mapped_column(Numeric(18, 2), nullable=False)
    confidence_score: Mapped[float] = mapped_column(Numeric(3, 2), nullable=False)
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level"),
        nullable=False,
    )
    effort_level: Mapped[EffortLevel] = mapped_column(
        Enum(EffortLevel, name="effort_level"),
        nullable=False,
    )
    status: Mapped[RecommendationStatus] = mapped_column(
        Enum(RecommendationStatus, name="recommendation_status"),
        default=RecommendationStatus.OPEN,
        nullable=False,
    )
    owner: Mapped[str | None] = mapped_column(String(255), nullable=True)
    explanation: Mapped[str | None] = mapped_column(Text, nullable=True)
