'use client';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { CheckCircle, XCircle, EyeOff, Download, Lightbulb } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Header } from '@/components/layout/header';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { recommendationsApi, type Recommendation } from '@/lib/api';
import { cn, formatCurrency } from '@/lib/utils';

const STATUS_OPTIONS = ['open', 'approved', 'rejected', 'executed', 'dismissed'];
const CATEGORY_OPTIONS = ['waste_detection', 'right_sizing', 'rate_optimization', 'governance'];
const RISK_OPTIONS = ['low', 'medium', 'high'] as const;

const statusVariant: Record<string, 'default' | 'success' | 'destructive' | 'secondary' | 'warning' | 'outline'> = {
  open: 'default',
  approved: 'success',
  rejected: 'destructive',
  dismissed: 'secondary',
  executed: 'warning',
};

const riskVariant: Record<string, 'success' | 'warning' | 'destructive'> = {
  low: 'success',
  medium: 'warning',
  high: 'destructive',
};

function exportCsv(recs: Recommendation[]) {
  const headers = [
    'id', 'rule_id', 'category', 'status', 'risk_level',
    'effort_level', 'estimated_monthly_savings', 'confidence_score',
    'short_description', 'resource_id',
  ];
  const rows = recs.map((r) =>
    headers.map((h) => JSON.stringify((r as unknown as Record<string, unknown>)[h] ?? '')).join(',')
  );
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `recommendations-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

function FilterPill({
  label,
  active,
  onClick,
  variant,
}: {
  label: string;
  active: boolean;
  onClick: () => void;
  variant?: 'green' | 'amber' | 'red';
}) {
  let activeClasses = 'bg-foreground text-background';
  if (variant === 'green' && active) activeClasses = 'bg-emerald-600 text-white';
  if (variant === 'amber' && active) activeClasses = 'bg-amber-500 text-white';
  if (variant === 'red' && active) activeClasses = 'bg-red-600 text-white';

  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'rounded-full px-3 py-1 text-xs font-medium transition-all',
        active ? activeClasses : 'bg-muted text-muted-foreground hover:bg-muted/80'
      )}
    >
      {label}
    </button>
  );
}

const riskPillVariant: Record<string, 'green' | 'amber' | 'red'> = {
  low: 'green',
  medium: 'amber',
  high: 'red',
};

export default function RecommendationsPage() {
  const [status, setStatus] = useState('');
  const [category, setCategory] = useState('');
  const [riskLevel, setRiskLevel] = useState('');
  const [page, setPage] = useState(1);
  const qc = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ['recommendations', status, category, riskLevel, page],
    queryFn: () =>
      recommendationsApi.list({
        status: status || undefined,
        category: category || undefined,
        risk_level: riskLevel || undefined,
        page,
        size: 20,
      }),
  });

  const mutOpts = {
    onSuccess: () => qc.invalidateQueries({ queryKey: ['recommendations'] }),
  };
  const approveMut = useMutation({ mutationFn: (id: string) => recommendationsApi.approve(id), ...mutOpts });
  const rejectMut = useMutation({ mutationFn: (id: string) => recommendationsApi.reject(id), ...mutOpts });
  const dismissMut = useMutation({ mutationFn: (id: string) => recommendationsApi.dismiss(id), ...mutOpts });

  const totalSavings = data?.items.reduce((s, r) => s + r.estimated_monthly_savings, 0) ?? 0;
  const total = data?.total ?? 0;

  return (
    <div className="flex flex-col">
      <Header
        title="Recommendations"
        description="Cost optimization opportunities generated by the rule engine"
      />
      <div className="flex-1 p-6 space-y-4">
        {/* Summary banner */}
        {data && total > 0 && (
          <div className="rounded-xl bg-gradient-to-r from-emerald-50 to-green-50 border border-emerald-200/60 px-5 py-4 flex items-center justify-between shadow-sm">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-100">
                <Lightbulb className="h-5 w-5 text-emerald-600" />
              </div>
              <div>
                <p className="text-sm font-semibold text-emerald-800">{total} recommendations found</p>
                <p className="text-xs text-emerald-600">Review and action to reduce spend</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-2xl font-bold text-emerald-700">{formatCurrency(totalSavings)}</p>
              <p className="text-xs text-emerald-600">potential savings/month</p>
            </div>
          </div>
        )}

        {/* Filter pills */}
        <div className="flex flex-wrap items-center gap-4">
          {/* Status filters */}
          <div className="flex flex-wrap gap-2 items-center">
            <span className="text-sm font-medium text-muted-foreground mr-1">Status:</span>
            <FilterPill
              label="All"
              active={status === ''}
              onClick={() => { setStatus(''); setPage(1); }}
            />
            {STATUS_OPTIONS.map((s) => (
              <FilterPill
                key={s}
                label={s.charAt(0).toUpperCase() + s.slice(1)}
                active={status === s}
                onClick={() => { setStatus(status === s ? '' : s); setPage(1); }}
              />
            ))}
          </div>

          <div className="h-6 w-px bg-border" />

          {/* Category filters */}
          <div className="flex flex-wrap gap-2 items-center">
            <span className="text-sm font-medium text-muted-foreground mr-1">Category:</span>
            <FilterPill
              label="All"
              active={category === ''}
              onClick={() => { setCategory(''); setPage(1); }}
            />
            {CATEGORY_OPTIONS.map((c) => (
              <FilterPill
                key={c}
                label={c.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())}
                active={category === c}
                onClick={() => { setCategory(category === c ? '' : c); setPage(1); }}
              />
            ))}
          </div>

          <div className="h-6 w-px bg-border" />

          {/* Risk filters */}
          <div className="flex flex-wrap gap-2 items-center">
            <span className="text-sm font-medium text-muted-foreground mr-1">Risk:</span>
            {RISK_OPTIONS.map((r) => (
              <FilterPill
                key={r}
                label={r.charAt(0).toUpperCase() + r.slice(1)}
                active={riskLevel === r}
                variant={riskPillVariant[r]}
                onClick={() => { setRiskLevel(riskLevel === r ? '' : r); setPage(1); }}
              />
            ))}
          </div>

          <div className="flex-1" />

          <Button
            variant="outline"
            size="sm"
            onClick={() => data && exportCsv(data.items)}
            disabled={!data || data.items.length === 0}
          >
            <Download className="h-4 w-4 mr-2" />
            Export CSV
          </Button>
        </div>

        {/* Table */}
        <Card className="shadow-sm">
          <CardHeader>
            <CardTitle>
              Recommendations {data ? `(${data.total})` : ''}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-3">
                {[...Array(5)].map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}
              </div>
            ) : (
              <>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Description</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Risk</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead className="text-right">Savings/mo</TableHead>
                      <TableHead className="text-right">Confidence</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {data?.items.map((rec) => (
                      <TableRow
                        key={rec.id}
                        className={cn(
                          'transition-colors',
                          rec.risk_level === 'high' && 'border-l-2 border-l-red-500',
                          rec.risk_level === 'medium' && 'border-l-2 border-l-amber-500',
                          rec.risk_level === 'low' && 'border-l-2 border-l-emerald-500'
                        )}
                      >
                        <TableCell>
                          <div>
                            <p className="text-sm font-medium">{rec.short_description}</p>
                            <p className="text-xs text-muted-foreground font-mono">{rec.rule_id}</p>
                          </div>
                        </TableCell>
                        <TableCell>
                          <span className="text-xs capitalize">
                            {rec.category.replace(/_/g, ' ')}
                          </span>
                        </TableCell>
                        <TableCell>
                          <Badge variant={riskVariant[rec.risk_level] ?? 'secondary'}>
                            {rec.risk_level}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant={statusVariant[rec.status] ?? 'outline'}>
                            {rec.status}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right font-semibold text-green-600">
                          {formatCurrency(rec.estimated_monthly_savings)}
                        </TableCell>
                        <TableCell className="text-right text-muted-foreground">
                          {(rec.confidence_score * 100).toFixed(0)}%
                        </TableCell>
                        <TableCell>
                          {rec.status === 'open' && (
                            <div className="flex gap-1">
                              <Button
                                variant="ghost"
                                size="icon"
                                title="Approve"
                                onClick={() => approveMut.mutate(rec.id)}
                                disabled={approveMut.isPending}
                              >
                                <CheckCircle className="h-4 w-4 text-green-600" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                title="Reject"
                                onClick={() => rejectMut.mutate(rec.id)}
                                disabled={rejectMut.isPending}
                              >
                                <XCircle className="h-4 w-4 text-red-500" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="icon"
                                title="Dismiss"
                                onClick={() => dismissMut.mutate(rec.id)}
                                disabled={dismissMut.isPending}
                              >
                                <EyeOff className="h-4 w-4 text-muted-foreground" />
                              </Button>
                            </div>
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                    {data?.items.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={7} className="text-center text-muted-foreground py-12">
                          No recommendations found with the current filters.
                        </TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>

                {/* Pagination */}
                {data && data.pages > 1 && (
                  <Card className="shadow-sm mt-4 border-0 border-t rounded-none">
                    <CardContent className="flex items-center justify-between py-4 px-0">
                      <p className="text-sm text-muted-foreground">
                        Page {data.page} of {data.pages} ({data.total} total)
                      </p>
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setPage((p) => Math.max(1, p - 1))}
                          disabled={page === 1}
                        >
                          Previous
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setPage((p) => p + 1)}
                          disabled={page >= data.pages}
                        >
                          Next
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                )}
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
