# AzCops Terraform Remote State — generated by bootstrap-spn.sh
terraform {
  backend "azurerm" {
    resource_group_name  = "AzCops-tfstate-rg"
    storage_account_name = "azcopsdevtf6c872c3280"
    container_name       = "tfstate"
    key                  = "azcops-dev.tfstate"
    use_azuread_auth     = true
  }
}
